# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6f5caeb36dcfcfb3da2e5e0bdcd9285c1d80bd158e97f76b596e7936a5cfcac79b7844f1b4dfe783fce0a070edd783d2a92aca5166258a9ffee6f4e286c44e8

test:
  secret_key_base: 3117eda9777664039ddfd898c3617250f78a07ae982fd4269cbfd9045d53417e644024731ad2f67b81ff89a7bf1685981096310c464a0b480c91c3675be40bb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
